//auth
export const SET_AUTH = "SET_AUTH";
export const AUTH_PROFILE = "AUTH_PROFILE";

//patient
export const UPDATE_PATIENTS = "UPDATE_PATIENTS";
export const UPDATE_PATIENT = "UPDATE_PATIENT";

//prescription
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const SET_DRUG_CANDIDATES = "SET_DRUG_CANDIDATES";
//SOAP Notes
export const SET_SOAP_STEP = "SET_SOAP_STEP";
export const SET_SOAP_CURRENT_STEP = "SET_SOAP_CURRENT_STEP";
export const SET_SOAP_DETAILS = "SET_SOAP_DETAILS";
export const SET_SOAP_ALL = "SET_SOAP_ALL";
export const SET_SOAP_LENGTH = "SET_SOAP_LENGTH";
export const SET_SOAP_MANDATORY_ITEM = "SET_SOAP_MANDATORY_ITEM";
